#!/bin/bash
#
### BEGIN INIT INFO
# Provides:          spamserver
# Required-Start:    $network $remote_fs $syslog
# Required-Stop:     $network $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start and stop the PeareScope Spam server daemon
# Description:       Controls the PeareScoe Spam server daemon
### END INIT INFO
#

NAME=$(/usr/bin/basename $0);

if [ "$(/usr/bin/whoami)" != "root" ]; then
    echo "You must run $0 as root" >&2
    exit 1
fi

case $1 in
    start)
        echo -n "Starting server: "
        /usr/bin/svc -u /etc/service/$NAME
        echo $NAME
        ;;

    stop)
        echo -n "Stopping server: "
        /usr/bin/svc -d /etc/service/$NAME
        echo $NAME
        ;;

    restart)
        $0 stop
        sleep 2
        $0 start
        ;;

    logrotate)
        echo -n "Reopening server log: "
        /usr/bin/svc -h /etc/service/$NAME
        echo $NAME
        ;;

    status)
        echo -n "Server $NAME is "
        svstat /etc/service/spamserver/ | awk '{print $2;}'
        ;;

    *)
        echo "Usage: $0 {start|stop|restart|logrotate|status}"
        exit 1
        ;;

esac

exit 0

